package com.airhoot.flight;


    public enum Airport {
        AMSTERDAM,
        ATLANTA,
        BARCELONA,
        BEIJING,
        BERLIN,
        CHENGDU,
        DALLAS,
        DELHI,
        DENVER,
        DUBAI,
        DUBLIN,
        EDINBURGH,
        FRANKFURT,
        HONG_KONG,
        ISTANBUL,
        JAKARTA,
        KINGSTON,
        KUALA_LUMPUR,
        LAS_VEGAS,
        LONDON,
        LOS_ANGELES,
        MADRID,
        MANILA,
        MEXICO_CITY,
        MIAMI,
        MOSCOW,
        MUMBAI,
        MUNICH,
        NEW_YORK,
        ORLANDO,
        OSAKA,
        PARIS,
        RIO_DE_JANEIRO,
        SAN_FRANCISCO,
        SEATTLE,
        SEOUL,
        SHANGHAI,
        SHENZHEN,
        SINGAPORE,
        SYDNEY,
        TAIPEI,
        TOKYO,
        TORONTO,
        WASHINGTON_DC

    }

